import type { FileProject, GuidePage, JumpLink, Level, Reward, WorkRecord, WorkspaceMember } from './types';

export const benefitProgramOptions = ['FR Partners', 'The Nick', 'RAIN HEART'] as const;

export const emptyMember: WorkspaceMember = {
  id: '',
  employmentId: '',
  fullName: '',
  preferredName: '',
  workStartDate: '',
  contractType: 'INDEPENDENT PARTNER',
  addressOfResidence: '',
  addressStreet: '',
  addressCity: '',
  addressState: '',
  addressPostalCode: '',
  addressCountry: '',
  citizenshipCountry: '',
  iban: '',
  withheldBalance: 0,
  personalEmail: '',
  slackTag: '',
  jobRole: '',
  entraEmail: '',
  entraObjectId: '',
  entraSetupCompleted: false,
  estimatedHours: '',
  phoneNumber: '',
  benefitPrograms: [],
  upworkUrl: '',
  timeZone: '',
  strikeSystem: 0,
  portfolio: '',
  rate: '',
  partnerStatus: 'available',
  partnerIndex: 100,
  completedTasks: 0,
  languages: '',
  software: '',
  seniority: '',
  employmentIdExpiresAt: '',
  skills: [],
  endorsedSkills: [],
  permissions: [],
  permissionDetails: [],
  upworkRequired: false,
  allowLegacyLogin: true,
  githubConnected: false,
  githubUsername: '',
  githubUserId: '',
  githubAvatarUrl: '',
  githubProfileUrl: '',
  onboarding: {
    gdprSigned: false,
    gdprUrl: '',
    ndaSigned: false,
    ndaUrl: '',
    completed: false,
    completedXpAwarded: false,
    contractType: 'None',
  },
  documents: [],
  issuedRewardIds: [],
  xp: 0,
  status: 'active',
  statusUntil: '',
  lastSeenAt: '',
  isAdmin: false,
  passwordHash: '',
  scheduleEnabled: false,
};

export const initialLevels: Level[] = [
  { id: 'level-1', number: 1, name: 'Level 1', xpRequired: 0, description: 'Workspace access unlocked.' },
  { id: 'level-2', number: 2, name: 'Level 2', xpRequired: 250, description: 'LevelUp! progress milestone.' },
  { id: 'level-3', number: 3, name: 'Level 3', xpRequired: 500, description: 'LevelUp! progress milestone.' },
  { id: 'level-4', number: 4, name: 'Level 4', xpRequired: 1000, description: 'LevelUp! progress milestone.' },
];

export const initialRewards: Reward[] = [
  { id: 'reward-1', levelId: 'level-2', rewardName: 'Flat Reality Sweatshirt', description: 'Unlocked at Level 2.' },
  { id: 'reward-2', levelId: 'level-3', rewardName: 'Priority workspace perks', description: 'Unlocked at Level 3.' },
];

export const initialJumpLinks: JumpLink[] = [
  { id: 'jump-1', title: 'Social Benefits', icon: 'HeartHandshake', url: 'https://tally.so/r/EkYpQq', order: 1 },
  { id: 'jump-4', title: 'Work Records', icon: 'ClipboardList', url: '#work-records', order: 2, internalView: 'workRecords' },
  { id: 'jump-6', title: 'Contact Head Office', icon: 'Building2', url: 'https://forms.office.com/r/LhHw6WFCgk', order: 3 },
  { id: 'jump-7', title: 'Career Growth', icon: 'TrendingUp', url: '#career-growth', order: 4, internalView: 'careerGrowth' },
  { id: 'jump-8', title: 'Signed Documents', icon: 'FileCheck2', url: '#signed-documents', order: 5, internalView: 'signedDocuments' },
  { id: 'jump-10', title: 'Files', icon: 'Folder', url: '#files', order: 6, internalView: 'files' },
  { id: 'jump-9', title: 'Installs', icon: 'Download', url: '#installs', order: 7, internalView: 'installs' },
];

export const initialFileProjects: FileProject[] = [
  { id: 'files-the-nick', name: 'The Nick', resources: [] },
  { id: 'files-rain-heart', name: 'RAIN HEART', resources: [] },
];

export const initialGuidePages: GuidePage[] = [
  {
    id: 'guide-1',
    title: 'Workspace Guide',
    content:
      '# Workspace Guide\n\nUse this area for internal documentation, operating rules, onboarding notes, and team resources.\n\n## Editing\n\nAdministrators can create and update guide pages from the Admin area.',
    order: 1,
  },
  {
    id: 'guide-partner-index',
    title: 'What is Partner Index?',
    content:
      '# What is Partner Index?\n\nPartner Index is a live quality signal for people assigned to Partners. It brings several work and profile signals together so the team can understand readiness, reliability, and recent contribution at a glance.\n\n## What helps your Index\n\nReliable delivery and completed assignments strengthen the Index over time. A complete professional profile, an established work history, and verified activity from connected work platforms also contribute.\n\nEndorsed skills add a small confidence boost. This bonus is deliberately limited, so collecting skill tags cannot outweigh real delivery and reliability.\n\n## What can lower it\n\nActive strikes have the strongest negative effect. Open requests for explanation also apply a small temporary reduction while the team is waiting for a response. Once an explanation is submitted, that temporary effect is removed automatically.\n\n## Fair by design\n\nThe Index uses balanced limits and diminishing effects. No single profile field, skill list, or connected platform can dominate the result. Availability status helps order the Partners board but does not directly rewrite the quality score; Inactive profiles are shown at the end of the list.\n\nThe exact weighting remains an internal operational model and may evolve as Workspace gains better verified data. Partner Index is a planning signal, not a measure of personal value and not a replacement for human review.',
    order: 2,
  },
];

export const initialMembers: WorkspaceMember[] = [
  {
    ...emptyMember,
    id: 'member-1',
    employmentId: 'FR-1001',
    fullName: 'Workspace Member',
    preferredName: 'Member',
    workStartDate: '2026-07-01',
    contractType: 'INDEPENDENT PARTNER',
    citizenshipCountry: 'Spain',
    personalEmail: 'member@example.com',
    jobRole: '3D Artist',
    estimatedHours: '20 hours / week',
    phoneNumber: '+34 600 000 001',
    benefitPrograms: ['FR Partners'],
    upworkUrl: 'https://www.upwork.com/',
    timeZone: 'Europe/Madrid',
    portfolio: 'https://portfolio.example.com',
    languages: 'English, Spanish',
    software: 'Blender, Unreal Engine',
    seniority: 'Mid-level',
    onboarding: {
      gdprSigned: true,
      gdprUrl: 'https://example.com/gdpr',
      ndaSigned: true,
      ndaUrl: 'https://example.com/nda',
      completed: false,
      completedXpAwarded: false,
      contractType: 'UPWORK CONTRACT',
    },
    documents: [
      { id: 'doc-member-1-nda', title: 'NDA', url: 'https://example.com/nda', signed: true, category: 'onboarding' },
      { id: 'doc-member-1-gdpr', title: 'GDPR', url: 'https://example.com/gdpr', signed: true, category: 'onboarding' },
    ],
    xp: 720,
  },
  {
    ...emptyMember,
    id: 'member-2',
    employmentId: 'FR-ADMIN',
    fullName: 'Workspace Administrator',
    preferredName: 'Admin',
    workStartDate: '2026-07-01',
    contractType: 'CORE TEAM',
    citizenshipCountry: 'Spain',
    personalEmail: 'admin@example.com',
    jobRole: 'Operations Manager',
    entraEmail: '',
    estimatedHours: 'Full-time',
    phoneNumber: '+34 600 000 002',
    benefitPrograms: ['FR Partners', 'The Nick'],
    upworkUrl: 'https://www.upwork.com/',
    timeZone: 'Europe/Madrid',
    languages: 'English, Spanish',
    software: 'Notion, Linear, Microsoft 365',
    seniority: 'Senior',
    onboarding: {
      gdprSigned: true,
      gdprUrl: 'https://example.com/gdpr',
      ndaSigned: true,
      ndaUrl: 'https://example.com/nda',
      completed: true,
      completedXpAwarded: true,
      contractType: 'MASTER SERVICE AGREEMENT',
    },
    documents: [
      { id: 'doc-member-2-nda', title: 'NDA', url: 'https://example.com/nda', signed: true, category: 'onboarding' },
      { id: 'doc-member-2-gdpr', title: 'GDPR', url: 'https://example.com/gdpr', signed: true, category: 'onboarding' },
    ],
    xp: 1420,
    isAdmin: true,
  },
];

export const initialWorkRecords: WorkRecord[] = [
  {
    id: 'record-1',
    memberId: 'member-1',
    type: 'standard',
    date: '2026-07-01',
    text: 'Workspace Member was registered as INDEPENDENT PARTNER for 3D Artist.',
    autoGenerated: true,
  },
  {
    id: 'record-2',
    memberId: 'member-2',
    type: 'standard',
    date: '2026-07-01',
    text: 'Workspace Administrator was registered as CORE TEAM for Operations Manager.',
    autoGenerated: true,
  },
];
