export type MemberStatus = 'active' | 'suspended' | 'sick_leave' | 'mental_health_days' | 'paused';
export type ContractType = 'CORE TEAM' | 'INDEPENDENT PARTNER';
export type BenefitProgram = 'FR Partners' | 'The Nick' | 'RAIN HEART';
export type OnboardingContractType = 'None' | 'MASTER SERVICE AGREEMENT' | 'UPWORK CONTRACT';
export type PartnerStatus = 'available' | 'working_hours' | 'inactive';
export type WorkRecordType = 'standard' | 'positive' | 'strike' | 'negative' | 'explanation_request';
export type ScheduleDayStatus = 'completed' | 'overworked' | 'day_off';
export type FileResourceType = 'Document file' | 'GitHub resource';

export type UpworkMoney = {
  amount: number;
  currency: string;
};

export type UpworkContract = {
  id: string;
  title: string;
  type: 'hourly' | 'fixed-price';
  rate: UpworkMoney | null;
  weeklyLimit: number | null;
  status: 'Active' | 'Paused' | 'Closed';
  startDate: string;
  endDate: string;
  currentMilestone: { id: string; description: string; amount: UpworkMoney } | null;
};

export type UpworkTimeEntry = {
  id: string;
  date: string;
  hours: number;
  charges: number;
  currency: string;
  contractId: string;
  contractTitle: string;
  memo: string;
};

export type UpworkSnapshot = {
  eligible: boolean;
  connected: boolean;
  available: boolean;
  connectionStatus: 'not_connected' | 'connected' | 'disabled' | 'error';
  message: string;
  lastSyncedAt: string;
  profile: {
    url: string;
    title: string;
    rate: UpworkMoney | null;
    photoUrl: string;
  } | null;
  contracts: UpworkContract[];
  payments: {
    earnings: UpworkMoney;
    fees: UpworkMoney;
    paid: UpworkMoney;
    pending: UpworkMoney;
    fixedPriceMilestones: UpworkMoney;
    withheldBalance: number;
    reconciledBalance: number;
  } | null;
  timeEntries: UpworkTimeEntry[];
};

export type UpworkContractDraft = {
  memberId: string;
  title: string;
  type: 'hourly' | 'fixed-price';
  rate: number;
  weeklyLimit: number;
  milestoneDescription: string;
  milestoneAmount: number;
  startDate: string;
  endDate: string;
};

export type AuditLogEntry = {
  id: string;
  eventType: string;
  actorMemberId: string;
  actorName: string;
  targetMemberId?: string;
  targetName?: string;
  summary: string;
  payload: Record<string, unknown>;
  createdAt: string;
};

export type WorkRecord = {
  id: string;
  memberId: string;
  type: WorkRecordType;
  date: string;
  text: string;
  relatedStrikeDate?: string;
  expiresAt?: string;
  explanationText?: string;
  explanationSubmittedAt?: string;
  autoGenerated?: boolean;
};

export type MemberDocument = {
  id: string;
  title: string;
  url: string;
  signed: boolean;
  category: 'onboarding' | 'other';
};

export type WorkspaceMember = {
  id: string;
  employmentId: string;
  fullName: string;
  preferredName: string;
  workStartDate: string;
  contractType: ContractType;
  addressOfResidence: string;
  addressStreet?: string;
  addressCity?: string;
  addressState?: string;
  addressPostalCode?: string;
  addressCountry?: string;
  citizenshipCountry: string;
  iban: string;
  withheldBalance: number;
  personalEmail: string;
  slackTag?: string;
  jobRole: string;
  entraEmail: string;
  entraObjectId: string;
  entraSetupCompleted: boolean;
  estimatedHours: string;
  phoneNumber: string;
  benefitPrograms: BenefitProgram[];
  upworkUrl: string;
  timeZone: string;
  strikeSystem: number;
  portfolio: string;
  rate: string;
  partnerStatus: PartnerStatus;
  partnerIndex: number;
  completedTasks: number;
  languages: string;
  software: string;
  seniority: string;
  employmentIdExpiresAt?: string;
  skills?: string[];
  endorsedSkills?: string[];
  permissions?: string[];
  permissionDetails?: string[];
  upworkRequired?: boolean;
  allowLegacyLogin?: boolean;
  githubConnected?: boolean;
  githubUsername?: string;
  pendingUpworkContract?: Omit<UpworkContractDraft, 'memberId'>;
  onboarding: {
    gdprSigned: boolean;
    gdprUrl: string;
    ndaSigned: boolean;
    ndaUrl: string;
    completed: boolean;
    completedXpAwarded: boolean;
    contractType: OnboardingContractType;
  };
  documents: MemberDocument[];
  issuedRewardIds: string[];
  xp: number;
  status: MemberStatus;
  statusUntil: string;
  lastSeenAt: string;
  isAdmin: boolean;
  passwordHash: string;
  scheduleEnabled: boolean;
};

export type ScheduleShift = {
  id: string;
  memberId: string;
  weekStart: string;
  dayIndex: number;
  startTime: string;
  endTime: string;
};

export type ScheduleDayCompletion = {
  id: string;
  memberId: string;
  weekStart: string;
  dayIndex: number;
  actualHours: number;
  completedAt: string;
};

export type Level = {
  id: string;
  number: number;
  name: string;
  xpRequired: number;
  description: string;
};

export type Reward = {
  id: string;
  levelId: string;
  rewardName: string;
  description: string;
};

export type JumpLink = {
  id: string;
  title: string;
  icon: string;
  url: string;
  order: number;
  internalView?: 'profile' | 'guides' | 'workRecords' | 'signedDocuments' | 'benefits' | 'installs' | 'levelup' | 'careerGrowth' | 'schedule' | 'files';
};

export type FileResource = {
  id: string;
  title: string;
  url: string;
  type: FileResourceType;
};

export type FileProject = {
  id: string;
  name: string;
  resources: FileResource[];
};

export type GuidePage = {
  id: string;
  title: string;
  content: string;
  order: number;
};

export type WorkspaceState = {
  members: WorkspaceMember[];
  levels: Level[];
  rewards: Reward[];
  guidePages: GuidePage[];
  workRecords: WorkRecord[];
  scheduleShifts: ScheduleShift[];
  scheduleCompletions: ScheduleDayCompletion[];
  fileProjects: FileProject[];
};
